name: "Create Release"

on:
    push:
        branches:
            - main
        tags:
            - v*

jobs:
    build:
        name: Create Release
        runs-on: ubuntu-20.04
        steps:
            - name: Checkout
              uses: actions/checkout@v2

            - name: Install Prerequisites
              run:  sudo apt-get update && sudo apt-get -y install pkg-config libusb-dev libgtk-3-dev gettext libconfig-dev

            - name: Build
              run: |
                  ./package.sh

            - name: Create Release
              id: create_release
              uses: actions/create-release@v1
              env:
                GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
              with:
                tag_name: ${{ github.ref }}
                release_name: OpenSuperClone ${{ github.ref }}
                draft: false
                prerelease: false

            - name: Upload Release Assets
              uses: alexellis/upload-assets@0.4.0
              env:
                GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
              with:
                asset_paths: '["./package/*"]'