name: "Create Release"

on:
    push:
        branches:
            - master
        tags:
            - v*

jobs:
    build:
        name: Create Release
        runs-on: ubuntu-latest
        steps:
            - name: Checkout
              uses: actions/checkout@v2

            - name: Install Prerequisites
              run:  sudo apt-get update && sudo apt-get -y install pkg-config libusb-dev libgtk-3-dev gettext libconfig-dev

            - name: Build
              run: |
                  ./package.sh

            - name: Create Release
              id: create_release
              uses: actions/create-release@v1
              env:
                GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
              with:
                tag_name: ${{ github.ref }}
                release_name: OpenSuperClone ${{ github.ref }}
                draft: false
                prerelease: false

            - name: Upload DEB
              uses: actions/upload-release-asset@v1
              env:
                GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
              with:
                upload_url: ${{ steps.create_release.outputs.upload_url }}
                asset_path: ./package/*.deb
                asset_name: OpenSuperClone-${{ github.ref }}_amd64.deb
                asset_content_type: application/zip